"""Download free-licensed ruler portraits from Wikimedia Commons into portraits.js.

Run:  python fetch_portraits.py
Only files hosted on Commons (free licenses / public domain) are kept; anything
else is skipped and the page falls back to a monogram.
"""
import base64, io, json, re, sys, time, urllib.parse, urllib.request
from PIL import Image

UA = {"User-Agent": "tw-history-anim/1.0 (personal educational project)"}
TITLES = [
    "Martinus Sonck", "Gerard Frederikszoon de With", "Pieter Nuyts", "Hans Putmans",
    "Johan van der Burgh", "Paulus Traudenius", "Maximiliaan le Maire", "François Caron",
    "Pieter Anthoniszoon Overtwater", "Nicolaes Verburg", "Cornelis Caesar", "Frederick Coyett",
    "Koxinga", "Zheng Jing", "Zheng Keshuang",
    "Kangxi Emperor", "Yongzheng Emperor", "Qianlong Emperor", "Jiaqing Emperor",
    "Daoguang Emperor", "Xianfeng Emperor", "Tongzhi Emperor", "Guangxu Emperor",
    "Liu Mingchuan", "Shao Youlian", "Tang Jingsong", "Liu Yongfu",
    "Kabayama Sukenori", "Katsura Tarō", "Nogi Maresuke", "Kodama Gentarō", "Sakuma Samata",
    "Andō Teibi", "Akashi Motojirō", "Den Kenjirō", "Uchida Kakichi", "Izawa Takio",
    "Kamiyama Mitsunoshin", "Kawamura Takeji", "Ishizuka Eizō", "Ōta Masahiro", "Minami Hiroshi",
    "Nakagawa Kenzō", "Seizō Kobayashi", "Kiyoshi Hasegawa", "Rikichi Andō",
    "Emperor Meiji", "Emperor Taishō", "Hirohito",
    "Chiang Kai-shek", "Chen Yi (Kuomintang)", "Wei Tao-ming", "Chen Cheng", "Li Zongren",
    "Yen Chia-kan", "Chiang Ching-kuo", "Lee Teng-hui", "Chen Shui-bian", "Ma Ying-jeou",
    "Tsai Ing-wen", "Lai Ching-te",
]

def get(url):
    for i in range(6):
        try:
            return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read()
        except Exception as e:
            if i == 5: raise
            time.sleep(15 * (i + 1))

def api(base, **p):
    p.update(format="json", formatversion="2")
    return json.loads(get(base + "?" + urllib.parse.urlencode(p)))

def strip(html):
    return re.sub(r"<[^>]+>", "", html or "").strip()

import os
CACHE = "portraits_cache.json"
out = json.load(open(CACHE, encoding="utf-8")) if os.path.exists(CACHE) else {}
missing = []
TITLES = [t for t in TITLES if t not in out]
for i in range(0, len(TITLES), 20):
    chunk = TITLES[i:i+20]
    r = api("https://en.wikipedia.org/w/api.php", action="query", prop="pageimages", piprop="name",
            titles="|".join(chunk), redirects=1)
    norm = {n["to"]: n["from"] for n in r["query"].get("normalized", [])}
    redir = {n["to"]: n["from"] for n in r["query"].get("redirects", [])}
    for pg in r["query"]["pages"]:
        t = pg["title"]; src = redir.get(t, t); src = norm.get(src, src)
        if "pageimage" not in pg: missing.append(src); continue
        fname = pg["pageimage"]
        ii = api("https://commons.wikimedia.org/w/api.php", action="query", prop="imageinfo",
                 titles="File:" + fname, iiprop="url|extmetadata", iiurlwidth=320)
        p = ii["query"]["pages"][0]
        time.sleep(1)
        if p.get("missing") or "imageinfo" not in p:
            missing.append(src + " (not on Commons)"); continue
        info = p["imageinfo"][0]; md = info.get("extmetadata", {})
        lic = md.get("LicenseShortName", {}).get("value", "")
        if md.get("NonFree", {}).get("value") in ("true", True):
            missing.append(src + " (non-free)"); continue
        img = Image.open(io.BytesIO(get(info["thumburl"]))).convert("RGB")
        w, h = img.size; tw = min(w, int(h * 0.8)); th = int(tw / 0.8)
        left = (w - tw) // 2; top = 0 if h > th else 0
        img = img.crop((left, top, left + tw, top + min(th, h))).resize((160, 200), Image.LANCZOS)
        buf = io.BytesIO(); img.save(buf, "JPEG", quality=82, optimize=True)
        out[src] = {
            "src": "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode(),
            "file": fname, "license": lic, "artist": strip(md.get("Artist", {}).get("value", ""))[:120],
            "url": info.get("descriptionurl", ""),
        }
        print("ok ", src, "|", lic, flush=True)
        json.dump(out, open(CACHE, "w", encoding="utf-8"), ensure_ascii=False)
        time.sleep(2)

with open("portraits.js", "w", encoding="utf-8") as f:
    f.write("// Generated by fetch_portraits.py from Wikimedia Commons. See credits in the page.\n")
    f.write("window.PORTRAITS = " + json.dumps(out, ensure_ascii=False) + ";\n")
print("\nsaved", len(out), "portraits")
print("missing:", *missing, sep="\n  ")
